# Add a connection IP address
# Your current IP address (197.94.216.137) has been added to enable local connectivity. Only an IP address you add to your Access List will be able to connect to your project's clusters. Add more later in Network Access.
# Create a database user
# This first user will have atlasAdmin  permissions for this project.

# We autogenerated a username and password. You can use this or create your own.

# You'll need your database user's credentials in the next step. Copy the database user password.
# Username: clementtshivhase
# Password: xFxaCoJ2T26LiYcq
# kv-cluster0.a7jjuyt.mongodb.net

